In [1]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [0]:
# load libraries
import numpy as np 
import pandas as pd 
import numpy as np, random, operator, pandas as pd, matplotlib.pyplot as plt
from numpy.random import randint
from random import random as rnd
from random import gauss, randrange
import re
import scipy.stats as st
import pathlib
import os
import os.path
import csv
import matplotlib.pyplot as plt
import matplotlib.ticker as mticker
import os
from networkx import *
from sklearn import preprocessing
import matplotlib
from sklearn import model_selection

from sklearn.datasets import make_classification
from matplotlib import pyplot as plt
from sklearn.linear_model import LogisticRegression
import seaborn as sns
sns.set()
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
import pandas as pd
import statsmodels

In [0]:
df = pd.read_excel("/content/drive/My Drive/nuovo.xlsx")

In [4]:
df['Age'].replace("30-49", 1, inplace=True)
df['Age'].replace("50+", 1, inplace=True)
df['Age'].replace("18-29", 0, inplace=True)
df.drop(axis=1, columns="index", inplace=True)
df.head()


Age  Gender  Education  ...  Stress  Comeback  more_than_three_years
0    1       0          1  ...       0         1                      0
1    1       1          1  ...       0         1                      0
2    1       0          1  ...       0         0                      0
3    1       0          1  ...       0         0                      0
4    1       1          1  ...       0         0                      1

[5 rows x 11 columns]

In [0]:
Y = df["Comeback"].tolist()


In [0]:
df.drop(axis=1, columns="Comeback", inplace=True)
df.drop(axis=1, columns="Gender", inplace=True)
df.drop(axis=1, columns="Toxic_people", inplace=True)


In [0]:
x_train, x_test, y_train, y_true = model_selection.train_test_split(df,Y,test_size = 0.33, stratify=df[['Age', "more_than_three_years"]] , random_state=1)

We instantiate an instance of the LogisticRegression class and call the fit function with the features and the labels (since Logistic Regression is a supervised machine learning algorithm) as arguments.

In [0]:
#from sklearn.preprocessing import StandardScaler
#sc = StandardScaler()
#sc.fit(x_train)
#x_train_std = sc.transform(x_train)
#x_test_std = sc.transform(x_test)

In [9]:
from sklearn.linear_model import LogisticRegressionCV

lr = LogisticRegressionCV(cv=100, random_state=1)
#>>> clf = LogisticRegressionCV(cv=5, random_state=0).fit(X, y)

lr.fit(x_train, y_train)

LogisticRegressionCV(Cs=10, class_weight=None, cv=100, dual=False,
                     fit_intercept=True, intercept_scaling=1.0, l1_ratios=None,
                     max_iter=100, multi_class='auto', n_jobs=None,
                     penalty='l2', random_state=1, refit=True, scoring=None,
                     solver='lbfgs', tol=0.0001, verbose=0)

In [10]:
df.head(2)

Age  Education  Abusive  ...  Lying  Stress  more_than_three_years
0    1          1        0  ...      1       0                      0
1    1          1        1  ...      0       0                      0

[2 rows x 8 columns]

In [11]:
print(lr.coef_)


[[-0.87450446  0.01926619  0.49028283 -0.25022964 -0.4148557  -0.15066223
   0.43388675  0.4788892 ]]


In [12]:
print(lr.intercept_)

[0.00713707]


Let’s see how the model performs against data that it hasn’t been trained on.

In [13]:
y_pred = lr.predict(x_test)
lr.classes_


array([0, 1])

**Confusion matrix**

In [14]:
conf = confusion_matrix(y_true, y_pred)
conf


array([[94, 24],
       [33, 32]])

**Precision and recall**

In [15]:
print("Precision: ")
conf[0, 0] / (conf[1,0]+conf[0,0])

Precision: 


0.7401574803149606

In [16]:
print("Recall: ")
conf[0, 0] / (conf[0,0]+conf[0,1])

Recall: 


0.7966101694915254

In [17]:

cmtx = pd.DataFrame(
    confusion_matrix(y_true, y_pred, labels=[0, 1]), 
    index=['true:yes', 'true:no'], 
    columns=['pred:yes', 'pred:no']
)
print(cmtx)

          pred:yes  pred:no
true:yes        94       24
true:no         33       32


In [0]:
x_test.to_csv('x_test.csv')
from google.colab import files
files.download('x_test.csv') 

If for whatever reason we’d like to check the actual probability that a data point belongs to a given class, we can use the predict_proba function. The first column corresponds to the probability that the sample belongs to the first class and the second column corresponds to the probability that the sample belongs to the second class.

In [0]:
lr_array = lr.predict_proba(x_test)


print the class order


In [20]:
lr.classes_


array([0, 1])

Print some specific cases and, then, the probability of theri classes

In [21]:
#x_test.reset_index(drop=True, inplace=True)
x_test.iloc[79]




Age                      0
Education                1
Abusive                  0
Cheating                 0
Unsupportive             0
Lying                    0
Stress                   1
more_than_three_years    1
Name: 87, dtype: int64

In [22]:
lr_array[79]


array([0.28106617, 0.71893383])

In [23]:
x_test.iloc[89]

Age                      0
Education                1
Abusive                  0
Cheating                 0
Unsupportive             1
Lying                    0
Stress                   1
more_than_three_years    1
Name: 58, dtype: int64

In [24]:
lr_array[89]


array([0.37184181, 0.62815819])